### ISSUE TITLE
Plans to convert a digraph to DAG?

### ISSUE THREAD

**Issue by rirze** [adaszko/roaring-graphs#1]
Hi,

Currently learning and figuring out how to use graphs and I found this library. Had a question whether this is possible:

Suppose I had a list of directed edges, but I don't know how to order the vertices such that they can be fed into this crate's DAG object. Is there a method where I feed these edges into the digraph object first and then do a sort where I can re-assign numbers to the vertices such that they satisfy a DAG?

From my understanding, a topological sort should be sufficient, but I may be wrong-- would this be possible do in the scope of this crate? 

Thanks

**Comment by adaszko** [comment]
Hi there!

> Suppose I had a list of directed edges, but I don't know how to order the vertices such that they can be fed into this crate's DAG object. Is there a method where I feed these edges into the digraph object first and then do a sort where I can re-assign numbers to the vertices such that they satisfy a DAG?

Nope, that's by design.  If you have a DAG object, it's already guaranteed to be a proper DAG.

> From my understanding, a topological sort should be sufficient, but I may be wrong-- would this be possible do in the scope of this crate?

This sounds right.  I just published a new crate version that adds the `DirectedGraph::get_topologically_ordered_vertices()` fn.  You should be able to use the returned sequence to assign consecutive numbers (starting from 0) to the vertices and build a map: `digraph_vertex -> dag_vertex`.  Having that, you can easily map any edge of a digraph to a new edge in the DAG.  Let me know if you come across any bugs!
